#!/usr/bin/env python3

import sys

from satsolver import parser
from satsolver import davis_putnam

def main():
    if len(sys.argv) != 2:
        print('Syntax: %s file.cnf' % sys.argv[0])
        exit()
    with open(sys.argv[1]) as fd:
        system = parser.parse(fd)
    print(repr(davis_putnam.solve(system)))

if __name__ == '__main__':
    main()
